#!/usr/bin/env bash
# script that transfers a file from our client to a server
if [ $# -lt 3 ]
then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	exit
else
	path_file="$1"
	ip_server="$2"
	username="$3"
	key="$4"
	scp -o StrictHostKeyChecking=no -i "$key" "$path_file" "$username@$ip_server:~/"
fi
