#!/usr/bin/env bash
#displays:The content of the current directoryIn a list format Where only the part of the name after the first dash is displayed (refer to the example)
for i in *; do
	echo "$i" | cut -f2 -d'-'
done